### ISSUE TITLE
Add filter by livemode

### ISSUE THREAD

**Issue by ctroms** [tighten/nova-stripe#18]
### Expected Behavior

Allow charge objects to be filtered by `livemode` from the Stripe API

### Resources 

* https://stripe.com/docs/api/charges/object#charge_object-livemode

**Comment by faxblaster** [comment]
Closing due to lack of support for `livemode` in search: https://stripe.com/docs/search#query-fields-for-charges

The only way I can think of to get around this would involve pulling all the charges, unpaginated, then filtering and returning a collection. Depending on the number of charges, this could quickly get resource-intensive.
